### PR TITLE
Partition search_clients_daily by sample_id

### PR DESCRIPTION
**Pull request by harterrt**
SCD is proving to be uncomfortably big for re:dash. Filtering by sample_id will make quick calculations easier.

### CODE REVIEW

**Comment by mreid-moz** [comment]
Drive-by: see the results of [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1434349) - it may be easier to sort by `sample_id` instead of partitioning.

**Comment by harterrt** [comment]
@mreid-moz - I only see references to Athena in that bug. Do those results apply to presto as well? This dataset will primarily be read from Presto.

**Comment by wlach** [comment]
Regardless, you will probably need to rebase this on master and fix some conflicts, as I just landed #191 (sorry for not doing that earlier!). The changes look fine to me, whether we decide to sort or partition.

**Comment by harterrt** [comment]
Rebased `search_dev` onto master and this PR onto `search_dev`. I'm going with orderBy for now. I'll backfill a few days to `search_clients_daily_dev` and make sure presto will correctly optimize reads.

**Comment by relud** [comment]
orderBy should work as well in presto as athena, because athena is presto under the hood, but ymmv

**Pull request merged**
