### PR TITLE
Features/fix iam role dynamo

### PR DESCRIPTION
**Pull request by crankycoder**
This fixes a minor bug with the taar_dynamo job in the dev enviroment where the IAM role is inherited directly from the cloud formation configuration.

This patch does not try to assume a new IAM role if no IAM role parameter is passed in.  

This has no impact to run the dynamo job in production.

### CODE REVIEW

**Comment by crankycoder** [comment]
@acmiyaguchi can you rerun the circleci tests?  these failures look like they're unrelated to my patch.

**Comment by acmiyaguchi** [comment]
Can you rebase to include https://github.com/mozilla/python_mozetl/pull/303, testpilot recently died and aren't serving requests anymore.

**Comment by crankycoder** [comment]
@acmiyaguchi sorry this rebase took so darn long.  The build looks clean now.

**Comment by acmiyaguchi** [comment]
This has been open for a while -- it looks like it shouldn't cause any issues, so I'll go ahead and merge this in.

**Pull request merged**
