### PR TITLE
[part 3] Enforce formatting with black

### PR DESCRIPTION
**Pull request by acmiyaguchi**
This is part 3 in a series to support python 3 in mozetl.

Black is a code formatting tool to keep style consistent across the code-base. It may help to reformat things in light of running other automated tools like 2to3. This is enforced in CI, so this fixes all of the tests introduced in #290.

This PR should be equivalent to #282.

### CODE REVIEW

**Comment by relud** [comment]
i'm going to wait to review this until it's a single commit of `format with black`

**Comment by relud** [comment]
@acmiyaguchi please re-request me for review once this has been rebased

**Comment by acmiyaguchi** [comment]
I also added `setup.py` and `bin/` to the linter, and re-enabled black linting on CI. Looking at some of the test failures, I might actually just separate them out into a separate PR.

**Comment by acmiyaguchi** [comment]
This was tested by running `tox -e flake8,black` locally.

**Pull request merged**
