### PR TITLE
Stop searchdb's `spark` so airflow exits quietly

### PR DESCRIPTION
**Pull request by harterrt**

### CODE REVIEW

**Comment by acmiyaguchi** [comment]
Do you have a snippet of the error that airflow spews?

**Comment by harterrt** [comment]
```
docker-compose run web airflow test main_summary search_dashboard 20170809
Waiting for db to listen on 5432...
Waiting for redis to listen on 6379...
[2017-08-21 21:08:37,512] {__init__.py:57} INFO - Using executor CeleryExecutor
[2017-08-21 21:08:37,776] {models.py:168} INFO - Filling up the DagBag from /app/dags
/usr/local/lib/python2.7/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing BaseHook directly from <module 'airflow.hooks' from '/usr/local/lib/python2.7/site-packages/airflow/hooks/__init__.pyc'> has been deprecated. Please import from '<module 'airflow.hooks' from '/usr/local/lib/python2.7/site-packages/airflow/hooks/__init__.pyc'>.[op
erator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  DeprecationWarning)
/usr/local/lib/python2.7/site-packages/airflow/utils/helpers.py:406: DeprecationWarning: Importing BashOperator directly from <module 'airflow.operators' from '/usr/local/lib/python2.7/site-packages/airflow/operators/__init__.pyc'> has been deprecated. Please import from '<module 'airflow.operators' from '/usr/local/lib/python2.7/site-packages/airflow/operator
s/__init__.pyc'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  DeprecationWarning)
[2017-08-21 21:08:38,107] {models.py:1128} INFO - Dependencies all met for <TaskInstance: main_summary.search_dashboard 2017-08-09 00:00:00 [None]>
[2017-08-21 21:08:38,110] {models.py:1128} INFO - Dependencies all met for <TaskInstance: main_summary.search_dashboard 2017-08-09 00:00:00 [None]>
[2017-08-21 21:08:38,110] {models.py:1328} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 3
--------------------------------------------------------------------------------

[2017-08-21 21:08:38,111] {models.py:1352} INFO - Executing <Task(EMRSparkOperator): search_dashboard> on 2017-08-09 00:00:00
[2017-08-21 21:08:38,128] {credentials.py:556} INFO - Found credentials in environment variables.
[2017-08-21 21:08:39,079] {connectionpool.py:735} INFO - Starting new HTTPS connection (1): us-west-2.elasticmapreduce.amazonaws.com
[2017-08-21 21:08:39,819] {emr_spark_operator.py:164} INFO - Running Spark Job Search Dashboard with JobFlow ID j-4X64NAIGOIKN
[2017-08-21 21:08:39,819] {emr_spark_operator.py:175} INFO - Logs will be available at: https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=telemetry-test-bucket&prefix=logs/harterrt@mozilla.com/Search Dashboard/j-4X64NAIGOIKN
[2017-08-21 21:08:39,969] {emr_spark_operator.py:203} INFO - Spark Job 'Search Dashboard' status' is STARTING
[2017-08-21 21:13:40,070] {connectionpool.py:238} INFO - Resetting dropped connection: us-west-2.elasticmapreduce.amazonaws.com
[2017-08-21 21:13:40,657] {emr_spark_operator.py:203} INFO - Spark Job 'Search Dashboard' status' is BOOTSTRAPPING
[2017-08-21 21:18:40,756] {connectionpool.py:238} INFO - Resetting dropped connection: us-west-2.elasticmapreduce.amazonaws.com
[2017-08-21 21:18:41,278] {emr_spark_operator.py:203} INFO - Spark Job 'Search Dashboard' status' is BOOTSTRAPPING
[2017-08-21 21:23:41,373] {connectionpool.py:238} INFO - Resetting dropped connection: us-west-2.elasticmapreduce.amazonaws.com
[2017-08-21 21:23:41,888] {emr_spark_operator.py:203} INFO - Spark Job 'Search Dashboard' status' is TERMINATING
[2017-08-21 21:28:41,989] {connectionpool.py:238} INFO - Resetting dropped connection: us-west-2.elasticmapreduce.amazonaws.com
[2017-08-21 21:28:42,589] {models.py:1427} ERROR - Spark job Search Dashboard terminated with errors: STEP_FAILURE - Shut down as step failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1379, in run
    result = task_copy.execute(context=context)
  File "/app/dags/operators/emr_spark_operator.py", line 193, in execute
    .format(self.job_name, reason_code, reason_message)
AirflowException: Spark job Search Dashboard terminated with errors: STEP_FAILURE - Shut down as step failed
[2017-08-21 21:28:42,590] {models.py:1443} INFO - Marking task as UP_FOR_RETRY
[2017-08-21 21:28:42,654] {models.py:1456} ERROR - Failed to send email to: ['telemetry-alerts@mozilla.com', 'harterrt@mozilla.com']
[2017-08-21 21:28:42,654] {models.py:1457} ERROR - [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1445, in handle_failure
    self.email_alert(error, is_retry=True)
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1605, in email_alert
    send_email(task.email, title, body)
  File "/usr/local/lib/python2.7/site-packages/airflow/utils/email.py", line 44, in send_email
    return backend(to, subject, html_content, files=files, dryrun=dryrun, cc=cc, bcc=bcc, mime_subtype=mime_subtype)
  File "/usr/local/lib/python2.7/site-packages/airflow/utils/email.py", line 86, in send_email_smtp
    send_MIME_email(SMTP_MAIL_FROM, recipients, msg, dryrun)
  File "/usr/local/lib/python2.7/site-packages/airflow/utils/email.py", line 104, in send_MIME_email
    s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) if SMTP_SSL else smtplib.SMTP(SMTP_HOST, SMTP_PORT)
  File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
[2017-08-21 21:28:42,662] {models.py:1472} ERROR - Spark job Search Dashboard terminated with errors: STEP_FAILURE - Shut down as step failed
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 28, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/airflow/bin/cli.py", line 585, in test
    ti.run(ignore_task_deps=True, ignore_ti_state=True, test_mode=True)
  File "/usr/local/lib/python2.7/site-packages/airflow/utils/db.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1379, in run
    result = task_copy.execute(context=context)
  File "/app/dags/operators/emr_spark_operator.py", line 193, in execute
    .format(self.job_name, reason_code, reason_message)
airflow.exceptions.AirflowException: Spark job Search Dashboard terminated with errors: STEP_FAILURE - Shut down as step failed
[2017-08-21 21:28:42,705] {connectionpool.py:735} INFO - Starting new HTTPS connection (1): us-west-2.elasticmapreduce.amazonaws.com
Makefile:33: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by harterrt** [comment]
Hmm. Looks like this is still failing locally for me. @acmiyaguchi could the issue be the newline [added here](https://github.com/mozilla/python_mozetl/commit/9eeff6b07baff68948087568c7c34796491ab77d#diff-7e88f747ab1936f9ef405568e4a5d9dfL88)?

**Comment by acmiyaguchi** [comment]
No, I don't think so, it shouldn't really matter. The cluster is not bootstrapping properly.

**Comment by harterrt** [comment]
How can you tell it's not bootstrapping properly? I think I see data from this test job in telemetry-test-bucket. I'll re-run this evening to verify.

**Comment by acmiyaguchi** [comment]
I'm looking at the EMR dashboard, it has some pretty useful diagnostics outside of airflow.

**Pull request merged**
